require("config.lazy")
require("config.options")
require("config.keymaps")
require("config.nvim-tree")
require("config.vimtex")
require("config.lsp")
require("config.filetypes")
require("config.telescope")
