require("config.lazy")
require("config.options")
require("config.keymaps")
require("config.nvim-tree")
require("config.vimtex")
require("config.lsp")
require("config.filetypes")
require("config.telescope")
require("config.lualine")
require("luasnip.loaders.from_lua").load({ paths = "~/.config/nvim/luasnippets" })
require("config.autocmds")
