[mgr]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "application/x-yaml", use = "edit" },
    { mime = "application/toml", use = "edit" },
    { url = "*.md", use = "edit" },
    { url = "*.tex", use = "edit" },
    { url = "*.bib", use = "edit" },
    { url = "*.py", use = "edit" },
    { url = "*.lua", use = "edit" },
    { url = "*.sh", use = "edit" },
    { url = "*.m", use = "edit" },
    { url = "*.R", use = "edit" },
    { url = "*", use = "edit" },
]
